<a href="https://colab.research.google.com/github/evertonnatan/tensorflow/blob/main/Introdu%C3%A7%C3%A3o_ao_TensorFlow_2_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## TensorFlow 1.X




### Instalando o TensorFlow 1.X



In [1]:
!pip uninstall -y tensorflow #Comando necessário, pois o TensorFlow-gpu não desinstala a versão mais recente do Tensorflow, pode gerar conflitos.

Found existing installation: tensorflow 2.7.0
Uninstalling tensorflow-2.7.0:
  Successfully uninstalled tensorflow-2.7.0


In [2]:
!pip install tensorflow-gpu==1.15 #Ignorar mensagem de erro

     |████████████████████████████████| 411.5 MB 8.8 kB/s 
     |████████████████████████████████| 3.8 MB 56.6 MB/s 
     |████████████████████████████████| 503 kB 71.3 MB/s 
     |████████████████████████████████| 50 kB 4.4 MB/s 
  Created wheel for gast: filename=gast-0.2.2-py3-none-any.whl size=7554 sha256=1dde5f4ff86cca63c7e76428abc43043e3fafb1fa88419f24ec5893467c3dd0e
  Stored in directory: /root/.cache/pip/wheels/21/7f/02/420f32a803f7d0967b48dd823da3f558c5166991bfd204eef3
Successfully built gast
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.7.0
    Uninstalling tensorflow-estimator-2.7.0:
      Successfully uninstalled tensorflow-estimator-2.7.0
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.7.0
    Uninstalling tensorboard-2.7.0:
      Successfully uninstalled tensorboard-2.7.0
  Attempting uninstall: gast
    Found existing installation: gast 0.4.0
    Uninstalling gast-0.4.0:
      Succe

In [3]:
import tensorflow as tf #Importando o TensorFlow

In [4]:
tf.__version__ #Verificando a versão instalada

'1.15.0'

### Constantes

#### Definindo uma constante

In [6]:
# Definindo uma constante no TensorFlow
tensor = tf.constant([[45, 6], [19, 23]])

In [7]:
tensor

<tf.Tensor 'Const_1:0' shape=(2, 2) dtype=int32>

In [8]:
# Se uma sessão não for inicializada, não podemos acessar os valores da constante
tensor.eval()

ValueError: ignored

#### Acessando os valores de uma constante

In [9]:
session = tf.Session()

In [11]:
session.run(tf.global_variables_initializer())

In [12]:
tensor_value = session.run(tensor)

In [13]:
tensor_value

array([[45,  6],
       [19, 23]], dtype=int32)

### Variáveis

#### Definindo uma variável

In [15]:
# Definindo uma variável no TensorFlow
variable = tf.Variable([[40, 30], [20, 90]])

In [16]:
variable

<tf.Variable 'Variable_1:0' shape=(2, 2) dtype=int32_ref>

In [17]:
# Se uma sessão na for inicializada, não podemos acessar os valores das variáveis
variable.eval()

ValueError: ignored

#### Acessando os valores de uma variável

In [18]:
# Inicializando uma sessão
session = tf.Session()

In [19]:
# Inicializando TODAS as variáveis de uma seção
session.run(tf.global_variables_initializer())

In [20]:
# Executando o método eval no ambiente com a sessão inicializada para conseguir buscar os valores
variable.eval(session)

array([[40, 30],
       [20, 90]], dtype=int32)

## TensorFlow 2.0

### Instalando o TensorFlow 2.0

In [21]:
!pip install tensorflow-gpu==2.0.0

     |████████████████████████████████| 380.8 MB 38 kB/s 
     |████████████████████████████████| 449 kB 59.3 MB/s 
     |████████████████████████████████| 3.8 MB 36.2 MB/s 
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 1.15.1
    Uninstalling tensorflow-estimator-1.15.1:
      Successfully uninstalled tensorflow-estimator-1.15.1
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 1.15.0
    Uninstalling tensorboard-1.15.0:
      Successfully uninstalled tensorboard-1.15.0
  Attempting uninstall: tensorflow-gpu
    Found existing installation: tensorflow-gpu 1.15.0
    Uninstalling tensorflow-gpu-1.15.0:
      Successfully uninstalled tensorflow-gpu-1.15.0


In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tf.__version__

'2.0.0'

### Constantes

#### Definindo uma constante

In [3]:
# Definindo uma constante no TensorFlow 2.0
tensor_20 = tf.constant([[13, 7], [12, 71]])

In [4]:
tensor_20

<tf.Tensor: id=0, shape=(2, 2), dtype=int32, numpy=
array([[13,  7],
       [12, 71]], dtype=int32)>

In [5]:
# Acessando as dimensões de um tensor
tensor_20.shape

TensorShape([2, 2])

#### Acessando os valores de uma constante

In [6]:
# Acessando os valores de um tensor com o numpy e sem precisar de uma sessão
tensor_20.numpy()

array([[13,  7],
       [12, 71]], dtype=int32)

In [7]:
# Podemos converter um numpy array para um tensor do TensorFlow
numpy_tensor = np.array([[65,  3], [12, 51]])

In [8]:
tensor_from_numpy = tf.constant(numpy_tensor)

In [9]:
tensor_from_numpy

<tf.Tensor: id=1, shape=(2, 2), dtype=int64, numpy=
array([[65,  3],
       [12, 51]])>

### Variáveis

#### Definindo uma variável

In [10]:
tf2_variable = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

#### Acessando os valores de uma variável

In [11]:
tf2_variable.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

#### Alterando um valor específico de uma variável

In [12]:
tf2_variable[0, 2].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

In [13]:
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

### Operações com tensores

In [14]:
tensor = tf.constant([[1, 2], [3, 4]])
tensor

<tf.Tensor: id=20, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

#### Adição entre um escalar e um tensor

In [15]:
tensor + 4

<tf.Tensor: id=22, shape=(2, 2), dtype=int32, numpy=
array([[5, 6],
       [7, 8]], dtype=int32)>

#### Multiplicação entre um escalar e um tensor

In [16]:
tensor * 5

<tf.Tensor: id=24, shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]], dtype=int32)>

#### Usando funções do numpy nos tensores do TensorFlow

In [18]:
# Obtendo o quadrado de todos os membros de um tensor
np.square(tensor)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [19]:
# Obtendo a raiz quadrada de todos os membros de um tensor
np.sqrt(tensor)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

#### Dot product (produto escalar) entre dois tensores

In [20]:
tensor

<tf.Tensor: id=20, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [21]:
tensor_20

<tf.Tensor: id=0, shape=(2, 2), dtype=int32, numpy=
array([[13,  7],
       [12, 71]], dtype=int32)>

In [22]:
 np.dot(tensor, tensor_20)

array([[ 37, 149],
       [ 87, 305]], dtype=int32)

### Strings no TensorFlow 2.0

In [23]:
tf_string = tf.constant("TensorFlow")
tf_string

<tf.Tensor: id=25, shape=(), dtype=string, numpy=b'TensorFlow'>

#### Operações simples com strings

In [24]:
tf.strings.length(tf_string)

<tf.Tensor: id=26, shape=(), dtype=int32, numpy=10>

In [25]:
tf.strings.unicode_decode(tf_string, "UTF8")

<tf.Tensor: id=30, shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114,  70, 108, 111, 119], dtype=int32)>

#### Armazenando arrays (vetores) de strings

In [26]:
tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])

In [27]:
# Iterating through the TF string array
for string in tf_string_array:
  print(string)

tf.Tensor(b'TensorFlow', shape=(), dtype=string)
tf.Tensor(b'Deep Learning', shape=(), dtype=string)
tf.Tensor(b'AI', shape=(), dtype=string)
